"""
Layout Code Generator
Converts a learned row_map (from learner.learn()) into a ready-to-deploy
engine/layout_X.py file and a detector additions snippet.

Usage:
    from engine import codegen
    code = codegen.generate_layout_code("C", "Apollo Fund XII", "GAAP", row_map, signals)
    detector_snippet = codegen.generate_detector_snippet("C", "Apollo Fund XII", signals)
"""


def generate_layout_code(
    letter:    str,
    fund_name: str,
    basis:     str,
    row_map:   dict,
    signals:   list,
) -> str:
    """
    Returns the full content of engine/layout_X.py as a string.
    """
    sig_repr = "\n".join(f'    "{s}",' for s in signals)

    header = f'''\
"""
Layout {letter} — {basis}
Fund: {fund_name}

Auto-generated by ILPA Processor · Layout Learner.
Review sign conventions (lines marked  # ← CHECK) before deploying.
"""

from .extractor import extract


def build_data(pdf_path: str, quarter: str = "") -> dict:
    """Return {{row_number: {{"E": qtd, "F": ytd, "G": si}}}}"""
    raw = extract(pdf_path)
    n   = raw["numbers"]

    def get(key, col):
        vals = n.get(key, [])
        return vals[col] if col < len(vals) else 0

    rows = {{}}

'''

    body_lines = []
    for row in sorted(row_map.keys()):
        cells = row_map[row]
        e = _expr(cells.get("E"))
        f = _expr(cells.get("F"))
        g = _expr(cells.get("G"))
        # Flag rows where a negation was applied so analyst can review
        needs_review = any(
            c.get("negate") for c in cells.values()
            if isinstance(c, dict)
        )
        suffix = "  # ← CHECK sign" if needs_review else ""
        body_lines.append(f"    rows[{row:2d}] = {{\"E\": {e}, \"F\": {f}, \"G\": {g}}}{suffix}")

    footer = f'''
    return rows


# ── Detection signals ──────────────────────────────────────────
SIGNALS = [
{sig_repr}
]

CHECKS = []          # add verification checks once mapping is confirmed
E51_RECONCILES = True
'''

    return header + "\n".join(body_lines) + footer


def generate_detector_snippet(
    letter:    str,
    fund_name: str,
    signals:   list,
) -> str:
    """
    Returns a snippet the user pastes into engine/detector.py to register
    the new layout.
    """
    sig_lines  = "\n".join(f'    "{s}",' for s in signals)
    fund_lower = fund_name.lower()

    return f'''\
# ── Add to detector.py ────────────────────────────────────────
# 1. Paste these signals into the LAYOUT_{letter}_SIGNALS list:

LAYOUT_{letter}_SIGNALS = [
{sig_lines}
]

# 2. Add to the FUND_NAMES dict:
#    "{letter}": ["{fund_lower}"],

# 3. Add a scoring branch in detect() after the existing elif blocks:
#    score_{letter.lower()} = sum(1 for kw in LAYOUT_{letter}_SIGNALS if kw in t)
#    if score_{letter.lower()} >= 2:
#        layout = "{letter}"
#        confidence = min(100, score_{letter.lower()} * 12)
'''


# ── internal helpers ──────────────────────────────────────────────────────────

def _expr(info: dict | None) -> str:
    """Convert a mapping entry into a Python expression string."""
    if info is None:
        return "None"
    t = info.get("type")
    if t == "zero":
        return "0"
    if t == "fixed":
        v = info["value"]
        return str(int(v)) if isinstance(v, float) and v == int(v) else repr(v)
    if t == "pdf":
        field = info["field"]
        col   = info["col"]
        base  = f'get("{field}", {col})'
        return f"-abs({base})" if info.get("negate") else base
    return "None"
